
---
name: CommitCheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CommitCheckJob:
    name: CommitCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # fetch-depth is needed to get the full list of commits
          # necessary for commit msg linting when a PR has 2 commits or more
          # to avoid getting ALL the commits, we get current commits + origin
          fetch-depth: ${{ github.event.pull_request.commits }} + 1
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - name: Checking commit quality (messages, signatures, etc)
        env:
          GIT_LAST: ${{ github.event.after }}
          GIT_ORIGIN: ${{ github.event.pull_request.base.sha }}
        run: |
          sh ./scripts/ci/prebuild.sh