name: UI test
on:
  workflow_run:
    workflows:
      - Commit Check
    types:
      - completed
    pull_request:
      branches: [ master ]
      paths:
        - 'ui/**'
jobs:
  UITest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: UI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: check commits
        run: git rev-list --all
      - name: check branch
        run: git branch
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '10'

      - name: Build
        working-directory: ./ui
        run: yarn

      - name: Test
        working-directory: ./ui/cap-react
        run: yarn prebuild
